//! The turn loop: one client prompt → model requests (streamed) →
//! assistant messages persisted, until the model finishes or the
//! request cap trips.
//!
//! v1 runs a single request per turn — the loop shape exists so
//! tool-call iterations (T-021: execute via the registry + pipeline,
//! append tool results, request again) slot in without reshaping.

use super::{ModelProvider, ModelRequest, TurnOutcome, TurnStop};
use crate::agent::{ChatMessage, ModelError};
use crate::store::{Message, Role, SessionStore, StoreError, TurnId};

#[derive(Debug, thiserror::Error)]
pub enum TurnError {
    #[error(transparent)]
    Model(#[from] super::ModelError),
    #[error(transparent)]
    Store(#[from] StoreError),
}

/// Runs one turn: persists the prompt turn (the user message) is the
/// CALLER's job — this loop persists the assistant response(s).
///
/// `assistant_message_id` is pre-generated by the caller so the streamed
/// chunks and the stored message share one stable identity (one
/// messageId per logical message).
/// `context_length_note` is the actionable message the context-length
/// failure surfaces in-band — the caller builds it naming the
/// configured compaction script (or its absence).
/// Arguments stay explicit (provider, store, ids, prompts, cap, callback):
/// the tool-call loop in T-021 extends the body, not the signature.
#[allow(clippy::too_many_arguments)]
pub async fn run_turn<P: ModelProvider>(
    provider: &P,
    db: &SessionStore,
    session_id: &crate::store::SessionId,
    turn_id: &TurnId,
    assistant_message_id: &str,
    model: &str,
    system: &str,
    prompt_text: &str,
    prior: Vec<ChatMessage>,
    max_requests: u32,
    #[allow(unused_variables)] // the usage callback owns the size decision (T-016 sends it)
    size: u64,
    context_length_note: &str,
    mut on_usage: impl FnMut(u64, u64, f64) + Send,
    mut on_delta: impl FnMut(&str) + Send,
    mut on_retry: impl FnMut(u32, &str) + Send,
) -> Result<TurnOutcome, TurnError> {
    let mut request_count = 0u32;
    let history = prior;

    // Never loops in v1: the model makes no tool requests, so the first
    // response ends the turn. The loop is the tool-call iteration seam
    // (T-021: execute tools via the registry, append results, request
    // again) — kept as the shape so the cap logic lives here.
    #[allow(clippy::never_loop)]
    loop {
        request_count += 1;
        if request_count > max_requests {
            // The caller announces in the client before mapping this onto
            // ACP's max_turn_requests stop reason (Quest F9).
            return Ok(TurnOutcome {
                stop: TurnStop::MaxTurnRequests,
                usage: db.session_usage(session_id).await?,
            });
        }

        let mut request_messages = history.clone();
        request_messages.push(ChatMessage {
            role: super::ChatRole::User,
            text: prompt_text.to_owned(),
        });
        let request = ModelRequest {
            model: model.to_owned(),
            system: system.to_owned(),
            messages: request_messages,
        };

        // The messageId: every streamed chunk carries the same identity —
        // chunks are fragments of ONE logical message (the stored assistant
        // message is appended below with exactly this id).
        let message_id = assistant_message_id.to_owned();
        let mut text = String::new();
        let mut deltas_flowed = false;
        let mut on_delta = |delta: &str| {
            deltas_flowed = true;
            text.push_str(delta);
            on_delta(delta);
        };
        let response = provider.stream_completion(request, &mut on_delta).await;
        let response = match response {
            Ok(response) => response,
            // A stream error with NO text: the failure happened before any
            // delta reached the client — retry like a plain transient.
            Err(ModelError::StreamFailed {
                error,
                text: partial,
                ..
            }) if partial.is_empty()
                && super::retry::classify(&error) == super::retry::FailureClass::Retryable
                && request_count < max_requests.min(super::retry::MAX_ATTEMPTS) =>
            {
                on_retry(request_count, &error);
                let delay = super::retry::retry_after_secs(&error)
                    .unwrap_or_else(|| super::retry::backoff(request_count));
                tokio::time::sleep(delay).await;
                continue;
            }
            // Mid-stream failure: the client already saw the deltas —
            // persist the partial text and answer with an in-band failure
            // notice (retrying would duplicate the streamed prefix).
            Err(ModelError::StreamFailed {
                text: partial,
                error,
                ..
            }) => {
                let note = format!(
                    "The model connection failed mid-response; the text above is partial. ({error})"
                );
                db.append_message(
                    turn_id,
                    Role::Assistant,
                    &serde_json::json!([
                        { "type": "text", "text": partial },
                        { "type": "text", "text": note }
                    ])
                    .to_string(),
                    None,
                    None,
                    None,
                    Some(&message_id),
                )
                .await?;
                return Ok(TurnOutcome {
                    stop: TurnStop::EndTurn,
                    usage: db.session_usage(session_id).await?,
                });
            }
            // Context-length: actionable, never retried (EC-003).
            Err(ModelError::Completion(text))
                if super::retry::classify(&text) == super::retry::FailureClass::ContextLength =>
            {
                // Actionable, never retried (EC-003): the caller's note
                // names the compaction script (or its absence).
                db.append_message(
                    turn_id,
                    Role::Assistant,
                    &serde_json::json!([{ "type": "text", "text": context_length_note }])
                        .to_string(),
                    None,
                    None,
                    None,
                    Some(&message_id),
                )
                .await?;
                return Ok(TurnOutcome {
                    stop: TurnStop::EndTurn,
                    usage: db.session_usage(session_id).await?,
                });
            }
            // Retryable without streamed deltas: back off and retry,
            // reporting the attempt as a status card. A retryable failure
            // WITH deltas is impossible (those arrive as StreamFailed).
            Err(ModelError::Completion(text))
                if super::retry::classify(&text) == super::retry::FailureClass::Retryable
                    && !deltas_flowed
                    && request_count < max_requests.min(super::retry::MAX_ATTEMPTS) =>
            {
                on_retry(request_count, &text);
                let delay = super::retry::retry_after_secs(&text)
                    .unwrap_or_else(|| super::retry::backoff(request_count));
                tokio::time::sleep(delay).await;
                continue;
            }
            Err(ModelError::Completion(text)) => {
                // Retries exhausted (or fatal): hard failure — the caller
                // surfaces a JSON-RPC error.
                return Err(TurnError::Model(ModelError::Completion(text)));
            }
            Err(err) => return Err(TurnError::Model(err)),
        };

        // Persist the assistant response with the SAME id the chunks used,
        // and the usage delta the request incurred.
        db.append_message(
            turn_id,
            Role::Assistant,
            &serde_json::json!([{ "type": "text", "text": response.text }]).to_string(),
            None,
            None,
            None,
            Some(&message_id),
        )
        .await?;
        db.set_turn_usage(
            turn_id,
            crate::store::TurnUsage {
                input_tokens: response.usage.input_tokens,
                output_tokens: response.usage.output_tokens,
                cost_usd: 0.0,
            },
        )
        .await?;
        on_usage(
            response.usage.input_tokens,
            response.usage.output_tokens,
            0.0,
        );

        // v1: the model made no tool requests (the tool-call loop lands in
        // T-021) — the response is the final answer.
        return Ok(TurnOutcome {
            stop: TurnStop::EndTurn,
            usage: db.session_usage(session_id).await?,
        });
    }
}

/// The prompt turn's user message content, stored as the JSON block array.
pub fn user_message_content(blocks: &serde_json::Value) -> String {
    match blocks {
        serde_json::Value::Array(_) => blocks.to_string(),
        other => serde_json::json!([other]).to_string(),
    }
}

/// The prompt text for the model: the text blocks' texts joined. Image
/// blocks are stored faithfully but do not reach the text seam in v1.
pub fn prompt_text(blocks: &[serde_json::Value]) -> String {
    blocks
        .iter()
        .filter_map(|block| block.get("text").and_then(serde_json::Value::as_str))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Helper retained for the tool-call loop (T-021): the message type is
/// constructed there with pre-generated ids.
#[allow(dead_code)]
fn message_for_append(id: String, turn_id: TurnId, role: Role, content: String) -> Message {
    Message {
        id,
        turn_id,
        role,
        content,
        tool_name: None,
        tool_call_id: None,
        is_error: None,
        position: 0,
        created_at: 0,
    }
}
