name: Setup Nix
description: Install Nix and configure Git for Nix flakes

runs:
  using: composite
  steps:
    - name: Install Nix
      shell: bash
      run: .github/actions/setup-nix/setup-nix.sh
    - name: Rewrite GitHub SSH URLs to HTTPS
      shell: bash
      run: .github/actions/setup-nix/setup-nix-git-config.sh
