npmMinimalAgeGate: 5

packageExtensions:
  "@algolia/autocomplete-js@*":
    peerDependencies:
      search-insights: "*"
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@cmfcmf/docusaurus-search-local@*":
    dependencies:
      "@docusaurus/theme-common": "*"
      "@docusaurus/utils-validation": "*"
      search-insights: "*"
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-css-cascade-layers@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/preset-classic@*":
    dependencies:
      "@algolia/client-search": "*"
      search-insights: "*"
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-mermaid@*":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
      "@mdx-js/react": "*"
  "@docusaurus/theme-search-algolia@*":
    dependencies:
      "@algolia/client-search": "*"
      search-insights: "*"
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
