import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// this runs in node.js - don't use client-side code here (browser apis, jsx...)

const sidebars: SidebarsConfig = {
  devSidebar: [{ type: "autogenerated", dirName: "dev" }],
  userSidebar: [{ type: "autogenerated", dirName: "user" }],
};

export default sidebars;
