name: Merge to main

on:
  push:
    branches: [main]

jobs:
  build-docs:
    name: Build docs
    permissions:
      contents: read
      pages: read
      id-token: write
    uses: ./.github/workflows/docs.build.yaml
  deploy-docs:
    name: Deploy docs
    needs: build-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/docs.deploy.yaml
