name: "Nix: update hashes"

on:
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
  workflow_dispatch: {}

concurrency:
  group: nix-update-hashes-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # To push cargo hash updates
    defaults:
      run:
        shell: nix develop ./nix --command bash -euo pipefail {0}
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check and update cargo hash
        id: update-hash
        run: just nix:update-hash
      - name: Commit and push
        if: >-
          steps.update-hash.outcome == 'success' &&
          !contains(github.event.pull_request.body, '#[no modification]')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/workflows/nix.update-hashes/commit-and-push-hash-update.sh
