name: "Nix: lint"

on:
  workflow_call: {}

concurrency:
  group: nix-lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Nix
        run: |
          sudo mkdir -p -m 0755 /nix
          sudo chown "${USER}" /nix
          curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
          . "${HOME}/.nix-profile/etc/profile.d/nix.sh"
          nix --version
      - name: Rewrite GitHub SSH URLs to HTTPS
        run: |
          git config --global --add url."https://github.com/".insteadOf "git+ssh://git@github.com/"
          git config --global --add url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://github.com/".insteadOf "git@github.com:"
          git config --global --get-all url."https://github.com/".insteadOf
      - name: Run flake check
        run: |
          . "${HOME}/.nix-profile/etc/profile.d/nix.sh"
          nix --extra-experimental-features 'nix-command flakes' flake check --show-trace ./nix
