name: "Nix: update hashes"

on:
  pull_request:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
  workflow_dispatch: {}

concurrency:
  group: nix-update-hashes-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # To push cargo hash updates
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Check and update cargo hash
        id: update-hash
        run: .github/workflows/nix.update-hashes/update-cargo-hash.sh
      - name: Commit and push
        if: steps.update-hash.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --exit-code --quiet nix/flake.nix; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add nix/flake.nix
            git commit -m "Update Nix cargo hash after dependency change"
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
            git push
          fi
