name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and test
    permissions:
      actions: write
      contents: read
    uses: ./.github/workflows/agentkit.build-and-test.yaml
  docs:
    name: Build docs
    permissions:
      contents: read
      pages: read
      id-token: write
    uses: ./.github/workflows/docs.build.yaml
  release-snapshot:
    name: Release snapshot
    permissions:
      actions: write
      contents: write
      # For keyless signing with cosign
      id-token: write
    uses: ./.github/workflows/agentkit.build-and-release.yaml
    with:
      build-is-snapshot: true
