name: "Workflows: lint"

on:
  workflow_call: {}

concurrency:
  group: workflows-lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Run actionlint
        run: .github/workflows/workflows.lint/lint-actionlint.sh
      - name: Run zizmor
        run: .github/workflows/workflows.lint/lint-zizmor.sh .github/workflows .github/dependabot.yaml
