name: "Workflows: lint"

on:
  workflow_call: {}

concurrency:
  group: workflows-lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - name: Run actionlint
        run: |
          bash <(curl -sS https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -ignore 'unexpected key "queue" for "concurrency" section'
      - name: Run zizmor
        run: |
          pip install zizmor
          zizmor .github/workflows .github/dependabot.yaml
